- backend/build.gradle
- backend/src/test/java/com/woowacourse/gongcheck/acceptance/AcceptanceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/documentation/DocumentationTest.java
- #10 
- `build.gradle` 내 documentation 생성을 위한 스크립트 추가
- `./gradlew bootJar` 실행 시 document 생성 스크립트
- `AcceptanceTest`추가 -> 차후 `DirtiesContext` 제거 필요
- `DocumentationTest` 추가 -> 사용 시 상속받은 후 `docsGiven` 사용 필요
> [BE] 인수테스트, 문서화테스트 환경을 세팅한다.

- backend/src/main/java/com/woowacourse/gongcheck/application/TaskService.java
- backend/src/main/java/com/woowacourse/gongcheck/domain/job/JobRepository.java
- backend/src/main/java/com/woowacourse/gongcheck/domain/task/RunningTask.java
- backend/src/main/java/com/woowacourse/gongcheck/domain/task/RunningTaskRepository.java
- backend/src/main/java/com/woowacourse/gongcheck/domain/task/Task.java
- backend/src/main/java/com/woowacourse/gongcheck/domain/task/TaskRepository.java
- backend/src/main/java/com/woowacourse/gongcheck/domain/task/Tasks.java
- backend/src/main/java/com/woowacourse/gongcheck/exception/BusinessException.java
- backend/src/main/java/com/woowacourse/gongcheck/exception/ControllerAdvice.java
- backend/src/main/java/com/woowacourse/gongcheck/presentation/TaskController.java
- backend/src/main/resources/data.sql
- backend/src/test/java/com/woowacourse/gongcheck/acceptance/TaskAcceptanceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/application/TaskServiceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/documentation/DocumentationTest.java
- backend/src/test/java/com/woowacourse/gongcheck/documentation/TaskDocumentation.java
- backend/src/test/java/com/woowacourse/gongcheck/domain/job/JobRepositoryTest.java
- backend/src/test/java/com/woowacourse/gongcheck/domain/task/RunningTaskRepositoryTest.java
- backend/src/test/java/com/woowacourse/gongcheck/domain/task/TaskRepositoryTest.java
- backend/src/test/java/com/woowacourse/gongcheck/domain/task/TaskTest.java
- backend/src/test/java/com/woowacourse/gongcheck/fixture/FixtureFactory.java
- backend/src/test/java/com/woowacourse/gongcheck/presentation/ControllerTest.java
- backend/src/test/java/com/woowacourse/gongcheck/presentation/TaskControllerTest.java
- #45 
1. `Host`를 찾는다
2. `Job`을 찾는다 (host와 jobid가 일치하도록 검증)
3. `Job`이 가지고있는 `Tasks`를 찾는다 (`Section` 무관 전체 `Tasks`를 찾는다)
4. 해당 `Tasks` 중 이미 `RunningTask`를 가진 `Task`가 있다면 예외를 발생시킨다
5. 없다면 진행중인 작업이 없으므로 `Tasks`로 `RunningTasks`를 만들고 전체 저장함으로써 새로운 진행작업을 추가한다
- `RunningTask`에서 `Task`를 `@MapsId`로 가지고 있었으나 `RunningTask`에서 `Task`를 가지고 사용할 일도 없을뿐더러 관계가 제대로 형성되지 않아 쿼리가 나가지 않음 -> 결국 `taskId`로만 사용하고 있으므로 해당 필드 제거
```java
boolean existsByTaskIdIn(@Param("taskIds") final List<Long> taskIds);
```
- `Task`들의 id list를 쉽게 가져오기위함
- `Task`들의 새로운 `RunningTask`를 쉽게 생성하기 위함
- `BusniessException`이라는 exception을 생성하였으나 해당 부분 어색할 시 리뷰 부탁드립니다
- `/api/jobs/{jobId}/tasks/new`
- 구현을 진행하다보니 jobs의 tasks들 중 새로운 무언가를 생성한다라는 의미를 전달하는 것이 더 맞다라고 판단
- `/api/jobs/{jobId}`만으로는 사실 rest하다라고 볼 수 없게 되어 보임 (id값에 대한 post는 resources를 …
> [BE] 공간 작업의 새로운 진행작업을 추가하는 API를 구현한다.

- backend/src/test/java/com/woowacourse/gongcheck/application/SpaceServiceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/documentation/SpaceDocumentation.java
- backend/src/test/java/com/woowacourse/gongcheck/domain/space/SpaceRepositoryTest.java
- #40 
- 기존에 테스트코드의 픽스쳐는 `test1`, `test2`처럼 임의의 문자열로 네이밍을 했습니다. 이를 실제 서비스에서 사용될 데이터와 유사한 이름으로 수정하였습니다. 예를 들어 `Space` 데이터의 픽스쳐의 네임 필드는 `잠실`과 같은 이름을 사용하도록 변경하였습니다.
> [BE] 테스트 픽스쳐 네이밍을 실제 데이터와 비슷하도록 수정한다

- backend/src/main/java/com/woowacourse/gongcheck/application/TaskService.java
- backend/src/main/java/com/woowacourse/gongcheck/application/response/RunningTaskResponse.java
- backend/src/main/java/com/woowacourse/gongcheck/application/response/RunningTasksResponse.java
- backend/src/main/java/com/woowacourse/gongcheck/application/response/RunningTasksWithSectionResponse.java
- backend/src/main/java/com/woowacourse/gongcheck/domain/task/RunningTask.java
- backend/src/main/java/com/woowacourse/gongcheck/domain/task/Task.java
- backend/src/main/java/com/woowacourse/gongcheck/domain/task/TaskRepository.java
- backend/src/main/java/com/woowacourse/gongcheck/domain/task/Tasks.java
- backend/src/main/java/com/woowacourse/gongcheck/presentation/TaskController.java
- backend/src/test/java/com/woowacourse/gongcheck/acceptance/TaskAcceptanceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/application/TaskServiceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/documentation/TaskDocumentation.java
- backend/src/test/java/com/woowacourse/gongcheck/fixture/FixtureFactory.java
- backend/src/test/java/com/woowacourse/gongcheck/presentation/TaskControllerTest.java
- #54 
```
1. Host를 찾는다 (host가 존재하지 않으면 예외 발생)
2. Job을 찾는다 (host와 jobid가 일치하지 않으면 예외 발생)
3. Job이 가지고있는 Tasks를 찾는다
4. 해당 Tasks중 RunningTask를 가진 Task가 없으면 예외를 발생시킨다
5. RunningTask를 가진 Task가 존재한다면 진행중인 작업이 있는 것이므로 Tasks로 RunningTasksResponse를 만들어 반환한다.
```
현재 RunningTask들을 조회하기 위해선 TaskId를 통해 조회해야 합니다.
이 행위가 부자연스러울 뿐더러 Task와 RunningTask가 거의 비슷하기 때문에 Task로 RunningTask를 조회하고 다시 RunningTask 부터 객체탐색을 시작하는 것이 비효율적으로 느껴집니다. 어차피 Task -> RunningTask 참조가 생겨도 조회만 할 것 이기 때문에 Task에 RunningTask 필드를 추가하였습니다.
1. 전에 삭제한 @MapsId를 이용한 Task 필드를 다시 복구하였습니다.
```java
@MapsId("taskId")
@OneToOne(fetch = FetchType.LAZY)
@JoinColumn(name = "task_id", nullable = false)
private Task task;
```
2. Task에도 RunningTask 연관관계 매핑을 추가하였습니다. 이와 동시에 N+1 쿼리 문제를 해결하기 위해 @EntityGraph를 사용했습니다.
```java
public class Task { …
```
> [BE] 진행중인 작업을 조회하는 API를 구현한다.

- backend/src/main/java/com/woowacourse/gongcheck/application/SubmissionService.java
- backend/src/main/java/com/woowacourse/gongcheck/domain/job/Job.java
- backend/src/main/java/com/woowacourse/gongcheck/domain/task/RunningTasks.java
- backend/src/main/java/com/woowacourse/gongcheck/presentation/SubmissionController.java
- backend/src/main/java/com/woowacourse/gongcheck/presentation/request/SubmissionRequest.java
- backend/src/test/java/com/woowacourse/gongcheck/acceptance/SubmissionAcceptanceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/application/SubmissionServiceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/application/TaskServiceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/documentation/DocumentationTest.java
- backend/src/test/java/com/woowacourse/gongcheck/documentation/SubmissionDocumentation.java
- backend/src/test/java/com/woowacourse/gongcheck/documentation/TaskDocumentation.java
- backend/src/test/java/com/woowacourse/gongcheck/domain/task/RunningTaskRepositoryTest.java
- backend/src/test/java/com/woowacourse/gongcheck/domain/task/RunningTasksTest.java
- backend/src/test/java/com/woowacourse/gongcheck/fixture/FixtureFactory.java
- backend/src/test/java/com/woowacourse/gongcheck/presentation/ControllerTest.java
- backend/src/test/java/com/woowacourse/gongcheck/presentation/SubmissionControllerTest.java
- #53 
전체 RunningTask 의 is_checked 컬럼이 true 인지 확인하기 위해 RunningTasks 라는 일급컬렉션을 만들어 모두 true 인지 확인하도록 구현했습니다. 개인적으론 조회 시에 컬럼이 모두 true 인지 boolean 으로 받아보고 싶은데 아직 방법을 찾지 못했네영..
```java
public static RunningTask RunningTask_생성(final Long taskId, final boolean isChecked) {
return RunningTask.builder()
.taskId(taskId)
.isChecked(isChecked)
.createdAt(LocalDateTime.now())
.build();
}
```
RunningTask 의 체크 여부를 판단하기 위한 테스트를 만드는 도중 픽스처가 Task 를 받는 것으로 한정되어 있더라구요. 개인적으론 엔티티도 taskId 를 필드로 가지고 있고 체크 여부를 설정할 수 있게끔 위처럼 수정하면 범용적으로 사용할 수 있을 것 같다고 생각했습니다.
```java
POST /api/jobs/{jobId}/complete HTTP/1.1
Authorization : Bearer jwt.token.here
{
"author": "제출자"
}
```
인수테스트 시나리오를 구성하기 위해선 체크하기 API 가 필요하더라구요. 일단 코드는 추가해두어서 추후에 병합되면 테스트 통과할 것 같습니다.
> [BE] 제출하기 API 를 구현한다.

- backend/src/main/java/com/woowacourse/gongcheck/config/WebConfig.java
- backend/src/main/java/com/woowacourse/gongcheck/presentation/AuthenticationInterceptor.java
- #65 
- `AuthenticationInterceptor`에서 OPTION method로 들어온 요청에 대한 허용
- configuration 내에서 모든 method에 대한 cors 해제
> [BE] 로컬환경을 위한 CORS에 대한 권한을 해제한다.

- backend/src/test/java/com/woowacourse/gongcheck/acceptance/AuthSupport.java
- backend/src/test/java/com/woowacourse/gongcheck/acceptance/JobAcceptanceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/acceptance/SpaceAcceptanceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/acceptance/SubmissionAcceptanceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/acceptance/TaskAcceptanceTest.java
- #42 
- 기존에 `GuestAuthAcceptanceTest` 를 제외한 모든 인수테스트에서 중복되는 메서드를 사용하고 있었기에, 이를 다른 클래스로 분리하여 static 으로 선언 후 import 하여 사용하도록 변경하였습니다.
> [BE] 인수테스트 내 중복되는 토큰 요청 메서드를 분리한다.

- backend/src/test/java/com/woowacourse/gongcheck/documentation/JobDocumentation.java
- backend/src/test/java/com/woowacourse/gongcheck/documentation/SpaceDocumentation.java
- backend/src/test/java/com/woowacourse/gongcheck/documentation/TaskDocumentation.java
- backend/src/test/java/com/woowacourse/gongcheck/fixture/FixtureFactory.java
- resolve #41
- documentation test에서 Service에 대한 mocking return값이 null이 들어오는 부분을 직접 id값을 입력받도록 수정
> [BE] 테스트 픽스쳐 생성 시 id값을 직접 넣을 수 있도록 변경한다.

- frontend/package-lock.json
- frontend/package.json
- frontend/src/errorBoundary/ErrorUserToken.tsx
- frontend/src/layouts/UserLayout/index.tsx
- resolve #161 
- 사용자(user) 토큰 관련 error boundary 구현
- 토큰이 만료될 경우,토큰이 없을 경우
- 로컬스토리지에 있는 토큰을 지우고 비밀번호 페이지로 이동한다.
- [error boundary props](https://github.com/bvaughn/react-error-boundary#errorboundary-props)
- [React ErrorBoundary 에러 핸들링 하기](https://velog.io/@rkd028/React-ErrorBoundary-%EC%82%AC%EC%9A%A9%ED%95%98%EC%97%AC-%EC%97%90%EB%9F%AC-%ED%95%B8%EB%93%A4%EB%A7%81-%ED%95%98%EA%B8%B0)
- [QueryErrorResetBoundary](https://tanstack.com/query/v4/docs/reference/QueryErrorResetBoundary?from=reactQueryV3&original=https://react-query-v3.tanstack.com/reference/QueryErrorResetBoundary)
> [FE] 사용자, 토큰 만료 시, 에러처리를 해야한다.

- backend/build.gradle
- resolve #153 
- `jacocoTestReport`가 실행되지 않아 SonarCloud에서 코드 커버리지에 대한 리포팅 메시지가 누락되어 전송됨
- `jacocoTestReport`가 `test` task 이후에 실행이 될 수 있도록 스크립트 수정
> [BE] jacocoTestReport task 누락을 해결한다.

- frontend/src/ErrorBoundary/ErrorHostToken.tsx
- frontend/src/layouts/HostLayout/index.tsx
- frontend/src/layouts/ManageLayout/index.tsx
- resolve #223 
- 관리자(host) 토큰이 유효하지 않을 경우 로그인 페이지로 이동한다.
고려할 사항
- react에서 다음과 같은 에러를 노출시키는데 DOM이 렌더링될때 다른 함수가 실행이되어서 발생하는 에러이다.
- 이런 에러를 처리하는 방법은 useEffect(사이드이펙트)로 함수를 실행시켜야 하는데 현재 에러 바운더리의 컴포넌트? 함수?를 실행시키는거라 잘 이해가 되지 않는다. 나중에 좀더 찾아 봐야겠다.
- 유저측 에러바운더리에서는 발생하지 않는다.
> [FE] API 호출 관련 로딩, 에러 처리를 한다.

- backend/src/docs/asciidoc/host.adoc
- backend/src/docs/asciidoc/hosts.adoc
- backend/src/docs/asciidoc/index.adoc
- backend/src/main/java/com/woowacourse/gongcheck/application/HostService.java
- backend/src/main/java/com/woowacourse/gongcheck/application/response/HostResponse.java
- backend/src/main/java/com/woowacourse/gongcheck/presentation/HostController.java
- backend/src/test/java/com/woowacourse/gongcheck/acceptance/HostAcceptanceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/application/HostServiceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/application/JobServiceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/documentation/HostDocumentation.java
- resolve #225 
- 호스트의 id를 조회할 수 있는 API입니다.
- adoc 문서 host -> hosts로 변경하였습니다.
> [BE] 호스트 아이디 조회 API 구현

- backend/src/main/java/com/woowacourse/gongcheck/application/JobService.java
- backend/src/main/java/com/woowacourse/gongcheck/application/SpaceService.java
- backend/src/main/java/com/woowacourse/gongcheck/application/response/GithubProfileResponse.java
- backend/src/main/java/com/woowacourse/gongcheck/config/JpaConfig.java
- backend/src/main/java/com/woowacourse/gongcheck/domain/host/Host.java
- backend/src/main/java/com/woowacourse/gongcheck/domain/job/Job.java
- backend/src/main/java/com/woowacourse/gongcheck/domain/section/Section.java
- backend/src/main/java/com/woowacourse/gongcheck/domain/space/Space.java
- backend/src/main/java/com/woowacourse/gongcheck/domain/submission/Submission.java
- backend/src/main/java/com/woowacourse/gongcheck/domain/task/RunningTask.java
- backend/src/main/java/com/woowacourse/gongcheck/domain/task/Task.java
- backend/src/test/java/com/woowacourse/gongcheck/domain/host/HostRepositoryTest.java
- backend/src/test/java/com/woowacourse/gongcheck/domain/job/JobRepositoryTest.java
- backend/src/test/java/com/woowacourse/gongcheck/domain/section/SectionRepositoryTest.java
- backend/src/test/java/com/woowacourse/gongcheck/domain/space/SpaceRepositoryTest.java
- backend/src/test/java/com/woowacourse/gongcheck/domain/space/SpaceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/domain/submission/SubmissionRepositoryTest.java
- backend/src/test/java/com/woowacourse/gongcheck/domain/task/RunningTaskRepositoryTest.java
- backend/src/test/java/com/woowacourse/gongcheck/domain/task/TaskRepositoryTest.java
- resolve #244
- `LocalDateTime.now()`로 된 로직들 전부 jpa 어노테이션으로 수정 진행하였습니다.
- 테스트에서 `Import(JpaConfig.class)`가 계속 반복되는데 차후 테스트 격리 어노테이션을 만들게된다면 고려할 지점이 될 수 있겠네요
- 일반적으로 많이들 사용하는 `BaseTimeEntity`라는 상위클래스를 두고 상속하는 방식이 아닌 어노테이션을 각각에 전부 달아주었습니다. 서비스 목적마다 다르겠지만 굳이 수정날짜가 필요하지 않은 엔티티들도 존재하기 때문에 해당 방식은 저희 코드에는 맞지 않아 보이네요
> [BE] EnableJpaAuditing을 추가한다.

- frontend/src/components/host/Navigation/index.tsx
- frontend/src/components/host/Navigation/styles.ts
- frontend/src/styles/theme.ts
- resolve #283 
- 선택된 공간을 네비게이션에서 색깔로 구분할 수 있다.
고려할 점
- DashBoard 페이지에서 네비게이션의 공간을 클릭하면 선택된 공간의 정보로 페이지를 구성하게 되는데, 다양한 API 호출이 동시에 일어나서 다음과 같은 이슈가 발생한다.
- 네비게이션에서 다른 공간을 선택하면 네비게이션에 존재하는 해당 공간의 배경 색깔이 변경되는게 `느리다`
- DashBoard에 있는 다른 컴포넌트들도 api를 호출해서 해당 컴포넌트를 렌더링 하는데 네비게이션의 공간 텍스트의 배경 색깔이 변경되는 것 보다 더 먼저 변경된다.
- 동시에 바뀌거나 네비게이션의 공간 텍스트 배경색깔이 먼저 변경되어야 하는데 이러한 문제가 발생하는 것은 데이터가 단방향으로 흘러야 하는데 여기저기서 필요에 의해 API를 fetch 하고 있는 점과 네비게이션이 동떨어져 있어서 이러한 문제가 발생하는 거 같다.
> [FE] 유저, 선택된 공간에 따라 Navigation 컴포넌트에 해당 공간의 색깔이 달라져야 한다.

- backend/build.gradle
- resolve #331 
- bootJar 진행 전 build 파일에 resource를 정상적으로 copy하도록 수정
> [BE] bootJar 실행 시 현재 어플리케이션에서 생성된 Restdocs를 포함하도록 수정한다.

- backend/src/main/resources/application-oauth.yml
- resolve #340 
- application-oauth.yml 파일이 공개 저장소에 노출되어 다시 삭제하였습니다.
> fix: 깃헙 oauth 정보 삭제

- backend/src/main/java/com/woowacourse/gongcheck/core/application/SpaceService.java
- backend/src/main/java/com/woowacourse/gongcheck/core/presentation/SpaceController.java
- backend/src/main/java/com/woowacourse/gongcheck/core/presentation/request/SpaceChangeRequest.java
- backend/src/main/java/com/woowacourse/gongcheck/core/presentation/request/SpaceCreateRequest.java
- backend/src/test/java/com/woowacourse/gongcheck/acceptance/SpaceAcceptanceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/core/application/SpaceServiceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/documentation/SpaceDocumentation.java
- resolve #349 
- 이미지 업로드기능 제거로 인하여 생성, 수정 시 `MultipartFile`을 받는 로직을 전체 제거
- 따라서 json request에서 imageUrl을 받도록 수정
- imageUrl에 대한 제한을 두고싶다라면 Url에 대한 dns 네임을 제한하는 것도 한가지 방법이 될 듯 함
> [BE] Space 생성, 수정 시 File input을 제거하고 url을 받도록 수정한다.

- frontend/src/components/host/ImageBox/useImageBox.ts
- frontend/src/components/host/SpaceInfo/index.tsx
- frontend/src/components/host/SpaceInfo/useSpaceInfo.ts
- frontend/src/pages/host/DashBoard/useDashBoard.tsx
- frontend/src/pages/host/SpaceUpdate/index.tsx
- resolve #369 
- 컴포넌트가 이전의 상태값을 계속 유지 해서 생기는 이슈였습니다.
- 상태값을 따로 빼서 SideEffect로 관리 했습니다.
- 그리고 useQuery key값이 페이지 마다 중복되어 이전의 값을 가져와서 key값을 변경했습니다.
> [FE] 공간 수정 후, DashBoard 페이지에 spaceInfo 정보가 바로 반영되지 않는 이슈를 해결한다.

- frontend/src/pages/user/Password/index.tsx
- frontend/src/pages/user/Password/styles.ts
- resolve #291 
- 실제 릴리즈 환경에서 유저가 password 입력에서 불편함을 느끼지않도록 화면 고려
기존 - SE 환경(* 실제 모바일 환경에서는 브라우저바가 있기때문에 더 가려짐)
변경 - SE 환경
> [FE] 사용자 password 페이지 화면 수정

- backend/src/test/java/com/woowacourse/gongcheck/documentation/JobDocumentation.java
- resolve #378 
- Job 수정, 생성 시 Restdocs 문서화에 누락된 ImageUrl, Description 필드를 추가하였습니다.
> feat: Job 생성, 수정 RestDocs에 누락된 필드를 추가

- frontend/public/index.html
- resolve #290 
- 구글 서치 콘솔에 production 홈페이지 url를 인식 시킨 뒤, 해당 meta 태그를 index.html에 넣어 둔다.
> [FE] 도메인을 구매하면 SEO 검색 최적화를 해야한다.

- frontend/src/components/user/TaskCard/index.tsx
- frontend/src/pages/user/TaskList/index.tsx
- resolve #380 
- 각 section, task의 imageUrl, description 유무에 따라 해당 컴포넌트 노출 유무를 결정한다.
- 각 section, task의 imageUrl, description 데이터로 모달을 노출한다.
> [FE] 사용자 체크리스트 api 호출 시, 응답받은 imageUrl, description 데이터를 화면에 렌더링 해야한다.

- backend/src/test/java/com/woowacourse/gongcheck/core/application/HostServiceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/core/application/SpaceServiceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/core/application/SubmissionServiceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/core/application/TaskServiceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/core/domain/submission/SubmissionRepositoryTest.java
- backend/src/test/java/com/woowacourse/gongcheck/fixture/FixtureFactory.java
- resolve #353 
- Service 테스트에서 Id가 notNull인지만 확인하는 등의 검증이 부족한 부분을 보완했습니다.
- 생성된 submission의 name이 올바른지도 검증하기 위해 `Submission_생성` 픽스쳐 메서드에 name을 주입 받는 것으로 수정했습니다.
- actual에서 get() 해온 변수명은 actual~로 지정했습니다 (ex. actual.getTasks() -> actualTasks)
> [BE] Service 테스트에 대한 구체적인 테스트 검증을 추가한다.

- frontend/src/ErrorBoundary/ErrorUserTask.tsx
> [FE] 서버에서 주는 에러메시지의 text를 정확히 체크 해야 한다.

- backend/src/main/java/com/woowacourse/gongcheck/auth/application/HostAuthService.java
- backend/src/main/java/com/woowacourse/gongcheck/auth/application/OAuthClient.java
- backend/src/main/java/com/woowacourse/gongcheck/auth/application/response/OAuthAccessTokenResponse.java
- backend/src/main/java/com/woowacourse/gongcheck/auth/application/response/SocialProfileResponse.java
- backend/src/main/java/com/woowacourse/gongcheck/auth/presentation/request/OAuthAccessTokenRequest.java
- backend/src/main/java/com/woowacourse/gongcheck/infrastructure/oauth/GithubOauthClient.java
- backend/src/test/java/com/woowacourse/gongcheck/acceptance/FakeHostAuthController.java
- backend/src/test/java/com/woowacourse/gongcheck/auth/application/HostAuthServiceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/infrastructure/oauth/GithubOauthClientTest.java
- resolve #294 
- Github과 관련된 기술을 사용하는 부분은 infrastructure 패키지에 있는 클래스 빼고는 다 OAuth로 이름을 변경했습니다.
Github과 달리 Slack을 쓰는 부분은 종속이 심하게 되어있어서 지금 당장 변경하기는 어려울것 같아 이것 먼저 PR 합니다.
>  [BE] 외부 라이브러리에 종속적인 코드/네이밍을 수정한다.

- backend/src/test/java/com/woowacourse/gongcheck/ApplicationTest.java
- backend/src/test/java/com/woowacourse/gongcheck/DatabaseCleanerExtension.java
- backend/src/test/java/com/woowacourse/gongcheck/SupportRepository.java
- backend/src/test/java/com/woowacourse/gongcheck/core/application/HostServiceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/core/application/SpaceServiceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/core/application/SubmissionServiceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/core/application/TaskServiceTest.java
- resolve #322
- repository를 항상 주입받는 것을 막기 위해 `SupportRespository`를 추가하였습니다.
- `save()`, `saveAll()`을 통해 저장 기능을 사용할 수 있습니다.
- `findById()`, `getById()`를 통해 id를 통한 검색 기능을 사용할 수 있습니다.
- repository를 setup에서 사용할 때 entitymanager에 영속성 컨텍스트가 남아있는 것을 제거하였습니다.
- 테스트 진행 시 영속성 컨텍스트가 남아 온전히 Service만의 테스트가 진행되지 않으므로 flush, clear를 통해 독립성을 조금 더 유지할 수 있도록 변경하였습니다. 
- Application의 테스트 진행 시 실제로 commit되는 것까지가 `@Service`의 역할이라고 판단, 해당 부분까지 테스트 진행할 수 있도록 변경점을 잡았습니다.
- 기존의 `@SpringBootTest`와 `@Transactional`조합으로는 commit이 날아가지 않으므로 온전히 한 트랜잭션의 모든 내용을 테스트하지 못한다고 판단하였습니다.
- 따라서 `DatabaseInitializer`를 매 테스트마다 진행시켜주는 `@ApplicationTest`를 추가하고 변환하였습니다.
테스트 코드의 길이가 길아 load dif를 해야 전체 파일이 보이는 코드가 있으니 확인하여 리뷰부탁드립니다
> [BE] 테스트에서 repository를 주입받고 값을 세팅하는 환경을 개선한다.

- backend/src/main/java/com/woowacourse/gongcheck/auth/presentation/request/GuestEnterRequest.java
- backend/src/test/java/com/woowacourse/gongcheck/documentation/GuestAuthDocumentation.java
- backend/src/test/java/com/woowacourse/gongcheck/documentation/HostAuthDocumentation.java
- backend/src/test/java/com/woowacourse/gongcheck/documentation/ImageUploadDocumentation.java
- backend/src/test/java/com/woowacourse/gongcheck/documentation/JobDocumentation.java
- backend/src/test/java/com/woowacourse/gongcheck/documentation/SpaceDocumentation.java
- backend/src/test/java/com/woowacourse/gongcheck/documentation/SubmissionDocumentation.java
- backend/src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
- resolve #366
- 기본적으로 request-fields.adoc의 default 필드는 path, type, description 입니다.
- 여기서 추가적으로 custom field를 추가하고 싶다면 src/test/resources/org/springframework/restdocs/template 아래에 request-fields.snippet 파일을 만들어 추가적인 필드를 명시해줘야 합니다.
```
request-fields.snippet
|===
|Path|Type|Nullable|Length|Description
{{#fields}}
|{{#tableCellContent}}`+{{path}}+`{{/tableCellContent}}
|{{#tableCellContent}}`+{{type}}+`{{/tableCellContent}}
|{{#tableCellContent}}{{#nullable}}true{{/nullable}}{{/tableCellContent}} --- (1)
|{{#tableCellContent}}{{#length}}{{length}}{{/length}}{{/tableCellContent}} --- (2)
|{{#tableCellContent}}{{description}}{{/tableCellContent}}
{{/fields}}
|===
```
request-fields.snippet에 있는 모든 필드는 기본적으로 모두 명시해줘야 테스트시 에러가 발생하지 않습니다.
하지만 nullable이나 length 필드의 경우 명시하지 않아도 되는 상황이 존재합니다.
따라서 …
> [BE] RestDocs request-fields.adoc에 nullable, length 필드를 추가한다.

- frontend/src/components/user/SectionInfoPreview/index.tsx
- frontend/src/hooks/useLazyImage.ts
- resolve #470 
- IntersectionObserver를 통해 이미지가 스크롤에 들어왔을때 로딩하는 useLazyImage 훅을 통해 이미지 LazyLoading 을 적용
> [FE] 작업 체크 페이지에 이미지 LazyLoading을 적용한다.

- backend/build.gradle
- backend/src/test/java/com/woowacourse/gongcheck/cucumber/AcceptanceContext.java
- backend/src/test/java/com/woowacourse/gongcheck/cucumber/AcceptanceSteps.java
- backend/src/test/java/com/woowacourse/gongcheck/cucumber/CucumberIntegrationTest.java
- backend/src/test/java/com/woowacourse/gongcheck/cucumber/steps/GuestAuthStepDefinitions.java
- backend/src/test/resources/features/guestAuth.feature
- resolve #184 
기본적인 환경 설정과 시나리오 코드 예시 하나를 추가했습니다.
저번에 함께 트러블슈팅을 할 때, H2 드라이버를 찾아올 수 없다는 에러가 발생했었는데요, 알고보니 큐컴버를 위한 클래스패스 설정에서 `runtimeOnly` 의존성이 설정이 안되어 있어서 그랬습니다.
아래와 같이 런타임 의존성도 패스에 추가하여 문제를 해결했습니다.
```groovy
configurations {
cucumberRuntime.extendsFrom(implementation, testImplementation, runtimeOnly)
}
...
task acceptanceTest() {
dependsOn assemble, compileTestJava
doLast {
javaexec {
main = "io.cucumber.core.cli.Main"
classpath = configurations.cucumberRuntime + sourceSets.main.output + sourceSets.test.output
args = [
'--plugin', 'pretty',
'--plugin', 'html:build/reports/cucumber/cucumber-report.html',
'--glue', 'com.woowacourse.gongcheck',
'src/test/resources/features']
}
}
}
```
gradle에 `check`라는 task가 있습니다. 여기 해당 태스크를 추가하면 빌드할 때 함께 돌아갑니다. `build`는 `check`에 의존하고 있습니다.
관련 문서: …
> [BE] 인수테스트에 cucumber를 적용하기 위한 환경을 설정한다.

- frontend/src/pages/host/DashBoard/useDashBoard.tsx
- frontend/src/utils/copy.ts
- resolve #515 
- HTTPS 에서 copy가 안되어서 deprecated 된 Wep API(document.execCommand('copy'))를 사용했는데, 
배포환경이 HTTPS로 변경되어서 navigator.clipboard.writeText 방식으로 변경한다.
- 문제상황은 issue에 적혀있음
> [FE] 링크 복사 방식 변경

- backend/src/main/java/com/woowacourse/gongcheck/exception/ControllerAdvice.java
- resolve #534 
SSE 만료 시 자동으로 `AsyncRequestTimeoutException`이 발생합니다. 연결이 만료되었을 때 자동으로 브라우저에서 재연결 요청을 하기 때문에 무시해도 되는 예외이지만 현재 이에 대한 예외처리가 없어서 error log에 이 예외가 계속 남습니다.
따라서 `ControllerAdvice`에서 해당 예외를 무시하는 코드를 추가하였습니다.
빈 코드블럭이 실수로 작성되었다는 오해를 피하고자 명시적으로 do nothing이라는 주석을 달았는데, 필요없다고 판단되면 코멘트 남겨주세요. 지우겠습니다.
> [BE] SSE timeout시 발생하는 예외 회피 코드 추가

- backend/src/main/java/com/woowacourse/gongcheck/core/application/SpaceService.java
- backend/src/test/java/com/woowacourse/gongcheck/core/application/HostServiceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/core/application/SpaceServiceTest.java
- resolve #517 
HostService와 SpaceServiceTest의 가독성을 개선해보았습니다. 
선언과 초기화가 분리되어 있다보니 해당 변수가 어떻게 초기화 되어있는지 확인하는 과정이 번거롭다고 판단했기 때문입니다. Context 부분은 테스트할 메서드의 입력 파라미터를 설명하는 것이 주 목적인데, 선언과 할당을 같이 하는 것이 이 목적을 더 잘 달성한다고 생각했습니다.
예를들어, changeSpace 메서드의 해피케이스는, `입력받은 Host가 존재하고 입력받은 Space가 입력받은 Host의 소유이며, 입력받은 ChangeSpaceRequest의 name이 기존에 있던 Space와 중복되지 않는 경우`입니다.
이를 Context에서 자세하게 서술하는 것은 불가능하다고 생각합니다. 또 이를 단순화하여 `존재하는 Host와 존재하는 Space를 입력받는 경우`라고 서술하면, 해피케이스의 Context를 불완전하게 전달하여 코드를 읽는 사람에게 잘못된 정보를 줄 수 있다고 생각합니다. 따라서 언해피 케이스는 다른 예외 Context에서 설명하고 해피케이스는 단순히 `올바른 입력을 받는 경우`라고 서술하였습니다.
---
이후 다른 서비스 테스트를 리팩토링하기 전에 샘플용으로 팀원들의 의견을 받아보고자 먼저 PR 날려봅니다.
추가적으로 
* SpaceService의 changeSpace 메서드의 테스트가 누락된 것을 발견하여 추가했습니다.
* SpaceService의 메서드 순서를 테스트 순서와 일관되도록 정렬하였습니다.
> [BE] HostServiceTest와 SpaceServiceTest를 개선한다

- frontend/webpack.dev.js
```js
output: {
publicPath: '/',
filename: 'js/bundle.js',
path: path.join(__dirname, '/dist'),
clean: true,
},
```
publicPath 추가
output.publicPath
번들 파일을 업로드 한 위치 (서버 루트에 상대적)
웹팩에서 발생하는 모든 URL이 publicPath 로 시작하도록 다시 작성
> [FE] 사용자 페이지를 찾을 수 없어서 Cypress 오류가 뜨던 현상 해결

- backend/build.gradle
- backend/src/main/resources/application-test.yml
- backend/src/test/java/com/woowacourse/gongcheck/acceptance/DatabaseInitializer.java
- backend/src/test/resources/schema.sql
- resolve #583
- local test 환경에서 mysql로 동작할 수 있도록 testcontainer를 추가하였습니다.
- mysql로 schema 및 코드들이 변경되었습니다.
- docker가 컴퓨터 환경에 맞지 않게 설치되어있다면 (arm인데 intell 강제 설치) 다시 설치하여야 호환이 빠릅니다.
> [BE] Mysql TestContainer 테스트 환경을 구성한다

- backend/src/test/java/com/woowacourse/gongcheck/core/application/TaskServiceTest.java
- resolve #550 
`@BeforeEach`를 제거하고 Context의 네이밍을 입력파라미터를 잘 설명하도록 수정하였습니다.
ex) 존재하지_않는_Host로_RunningTask를_생성할_경우 -> 입력받은_Host가_존재하지_않는_경우
> [BE] TaskServiceTest beforeEach 제거 및 테스트 메서드 네이밍 개선

- backend/src/main/java/com/woowacourse/gongcheck/core/presentation/request/JobCreateRequest.java
- backend/src/main/java/com/woowacourse/gongcheck/core/presentation/request/SectionCreateRequest.java
- backend/src/main/java/com/woowacourse/gongcheck/core/presentation/request/TaskCreateRequest.java
- backend/src/test/java/com/woowacourse/gongcheck/acceptance/JobAcceptanceTest.java
- resolve #592 
기존에 Job 생성 시, Section의 Task가 비어있어도 저장 로직이 정상 수행된다.
DTO에서 Job저장 시, Section 값이 비어있는지 or Section에 해당하는 Task가 비어있지는 않은지 체크하는 검증을 추가했습니다.
DTO에 추가한 이유는 다음과 같습니다.
양방향 매핑이 되어있다면 Section에서 Task가 비어있는지 체크할 수 있겠지만, 현재는 단방향으로 되어 있습니다.
그렇다면 Service에서 검증해야 하는데, 결국 DTO에 값이 비어있지 않은지를 Service에서 체크해줘야 합니다.
때문에 이 로직을 Service에 추가하는 것 보다 DTO로 변환하는 과정에서 체크하는 것이 더 적합하다 생각해서 현재 로직으로 작성했습니다.
> [BE] Job 저장 시, Task가 존재하지 않으면 예외 발생하지 않는 문제 해결

- backend/src/main/java/com/woowacourse/gongcheck/core/application/TaskService.java
- backend/src/main/java/com/woowacourse/gongcheck/core/domain/task/TaskRepository.java
- resolve #553 
**1. Task-Running_Task 조회 시 문제.**
Task과 Running_task의 연관관계는 OneToOne입니다.
따라서 Task를 조회할 때, Running_Task를 함께 조회해 오지 않는다면, Task의 개수 만큼 조회 쿼리가 발생하게 됩니다.
(ex. 100개의 Task를 조회하는 쿼리 1개 발생 시, 100개의 Running_Task 조회 쿼리가 발생합니다.)
이를 Task 조회 시, Running_Task도 함께 fetch join을 사용하여 한 번에 조회하게 수정했습니다.
**2. Task 조회 시, Section 지연 로딩 문제**
전형적인 n+1 문제 발생 상황입니다.
Task 리스트를 조회하여 DTO로 변환 시, Task의 Section을 필요로 하기 때문에
조회한 Task 개수 n만큼의 조회 쿼리가 추가적으로 발생하게 됩니다.
따라서 해당 메서드는 Task조회 시, fetch join을 사용하여 Section도 한 번에 조회하게 수정했습니다.
자세한 내용은 [링크](https://meatsby.notion.site/N-1-1d0e66ca615b409dbc7380e856bb541e)로 정리했으니, 참고해 보시면 좋을 것 같습니다.
> [BE] N+1 발생하는 지점 파악 후 해결한다. 

- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/user/TaskList/useTaskList.tsx
- resolve #617
- SockJS 없이 stomp 만으로 웹소켓을 구현한다.
- SockJS는 웹소켓을 지원하지 않는 브라우저에서 socket과 비슷한 환경을 제공해주는 라이브러리이다.
- 백엔드의 웹소켓 부하 테스트 과정에서 SockJS가 어울리지 않다는 의견이 있어서, SockJS에 대한 의존성을 제거한다.
> [FE] SockJs를 제거한다.

- backend/src/main/java/com/woowacourse/gongcheck/config/WebConfig.java
- backend/src/main/java/com/woowacourse/gongcheck/config/WebSocketConfig.java
- backend/src/main/java/com/woowacourse/gongcheck/core/presentation/HostController.java
- backend/src/test/java/com/woowacourse/gongcheck/acceptance/HostAcceptanceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/core/application/SubmissionServiceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/documentation/HostDocumentation.java
- resolve #613 
- 기존에 `Host` 만 조회할 수 있던 profile 을 `Guest` 입장 페이지에서도 요구하도록 요구사항이 변경됨에 따라 api 를 수정하였습니다.
- api endpoint 는 `/api/hosts/me` -> `/api/hosts/{hostId}/profile` 로 변경되었습니다.
- 테스트 역시 토큰을 사용하지 않는 방식으로 변경하였습니다.
- H2 이슈로 인해 항상 성공하지 못하는 테스트를 제거하였습니다.
> [BE] Host profile 조회 api 를 구현한다.

- backend/src/main/java/com/woowacourse/gongcheck/core/application/HostService.java
- backend/src/main/java/com/woowacourse/gongcheck/core/presentation/HostController.java
- backend/src/test/java/com/woowacourse/gongcheck/acceptance/AcceptanceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/acceptance/HostAcceptanceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/core/application/HostServiceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/core/application/SubmissionServiceTest.java
- backend/src/test/java/com/woowacourse/gongcheck/documentation/HostDocumentation.java
- resolve #621 
- host `id`를 받아 프로필 조회하던 api를 `entranceCode` 를 통해 조회할 수 있도록 API 를 수정하였습니다.
- 추가로 동시 제출 테스트코드를 수정하였습니다.
- 해싱된 hostId 값인 `entranceCode` 라는 네이밍이 적절하지 않을 수 있을 것 같습니다. 새로운 네이밍에 대해 의논해보면 좋을 것 같습니다.
> [BE] Host profile 조회하는 api를 EntranceCode를 받도록 수정한다.

- frontend/tsconfig.json
- resolve #634
- babel로 컴파일을 진행하기때문에 tsconfig의 컴파일 관련은 전부 제거하였습니다.
- stict 모드와 중첩되는 사항은 제거하였습니다.
```json
// strict: true
{
"alwaysStrict": true,
"strictNullChecks": true,
"strictFunctionTypes": true,
"strictBindCallApply": true,
"strictPropertyInitialization": true,
"noImplicitAny": true,
"noImplicitThis": true,
"useUnknownInCatchVariables": true,
}
```
- 그 외의 변경된 옵션에 대한 설명은 코멘트로 남기겠습니다.
> [FE] 타입스크립트 옵션을 프로젝트에 맞게 수정한다.

- frontend/src/pages/user/TaskList/useTaskList.tsx
- resolve #636
- stomp.js reconnect_delay 1초로 설정
> [FE] 작동이 없어서 웹소켓 연결이 종료되었을때, 재연결을 할 수 있도록 한다.
