woowacourse-teams/2022-gong-check

frontend/.eslintrc.json, frontend/.gitignore, frontend/.prettierrc.json, frontend/babel.config.json, frontend/package-lock.json, frontend/package.json, frontend/public/index.html, frontend/src/App.tsx, frontend/src/index.tsx, frontend/tsconfig.json, frontend/webpack.config.js
- #1 
- tsconfig.json
```javascript
{
"compilerOptions": {
"target": "es2016", /* 사용할 특정 ECMAScript 버전 설정 (기본:ES3) */
"composite": true, /* 프로젝트 컴파일 여부 - 필요없는 컴파일을 피하기 위히여 */
"jsx": "react-jsx", /* JSX 코드를 어떻게 컴파일 할지 여부 */
"module": "commonjs", /* JS 파일간의 import 문법을 구현할 떄의 문법 결정 (commonJS: rueqire 문법 사용) */
"moduleResolution": "node", /* 모듈의 해석 방법 설정 (Node.js) */
"resolveJsonModule": true, /* JSON 파일을 import 할 것 인지 여부 */
"allowJs": true, /* JS 파일 컴파일 허용 여부 */
"noEmit": true, /* 결과 파일을 내보낼지 허용 여부(.d.ts / sourceMap) */
"isolatedModules": true, /* 파일을 모듈로 분리할지 여부 */
"allowSyntheticDefaultImports": true, /* default export가 아닌 모듈도 default import가 가능하게할지 여부  */
"esModuleInterop": true, /* 모든 imports에 대한 namespace 생성(CommonJS와 ES Modules 간의 상호 작용 가능)('allowSyntheticDefaultImports'가 true로 설정됨) */ …
```
=> [FE] 리액트 기반 환경설정을 한다. 

.gitignore
- #8 
- 이슈 생성 시점에서 `.gitignore`가 누락되었으나 `.gitignore` 생성되어 해당 파일을 수정하는 형태로 진행됨
- intelllij, vscode, mac에서 자동생성되는 캐싱파일을 ignore하도록 수정
=> [ALL] root 디랙토리를 관리하는 gitignore를 수정한다. 

backend/src/main/java/com/woowacourse/gongcheck/application/GuestAuthService.java, backend/src/main/java/com/woowacourse/gongcheck/application/JobService.java, backend/src/main/java/com/woowacourse/gongcheck/application/SpaceService.java, backend/src/main/java/com/woowacourse/gongcheck/application/TaskService.java, backend/src/main/java/com/woowacourse/gongcheck/domain/host/Host.java, backend/src/main/java/com/woowacourse/gongcheck/domain/host/HostRepository.java, backend/src/main/java/com/woowacourse/gongcheck/domain/job/JobRepository.java, backend/src/main/java/com/woowacourse/gongcheck/domain/member/MemberRepository.java, backend/src/main/java/com/woowacourse/gongcheck/domain/space/Space.java, backend/src/main/java/com/woowacourse/gongcheck/domain/space/SpaceRepository.java, backend/src/main/resources/data.sql, backend/src/main/resources/schema.sql, backend/src/test/java/com/woowacourse/gongcheck/application/GuestAuthServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/application/JobServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/application/SpaceServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/application/TaskServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/documentation/JobDocumentation.java, backend/src/test/java/com/woowacourse/gongcheck/documentation/SpaceDocumentation.java, backend/src/test/java/com/woowacourse/gongcheck/domain/host/HostTest.java, backend/src/test/java/com/woowacourse/gongcheck/domain/job/JobRepositoryTest.java, backend/src/test/java/com/woowacourse/gongcheck/domain/space/SpaceRepositoryTest.java, backend/src/test/java/com/woowacourse/gongcheck/domain/task/RunningTaskRepositoryTest.java, backend/src/test/java/com/woowacourse/gongcheck/domain/task/TaskRepositoryTest.java, backend/src/test/java/com/woowacourse/gongcheck/fixture/FixtureFactory.java, backend/src/test/resources/schema.sql
- #25 
- `Member`로 되어있는 domain, package, 변수 전체 `Host`로 변경
=> [BE] Member객체를 Host로 네이밍 전환한다.

backend/src/main/java/com/woowacourse/gongcheck/application/response/GuestTokenResponse.java, backend/src/main/java/com/woowacourse/gongcheck/exception/ErrorResponse.java, backend/src/main/java/com/woowacourse/gongcheck/presentation/request/GuestEnterRequest.java
- #20
- `@Getter`로 적용되어있지 않은 getter를 수정한다
=> [BE] @Getter 어노테이션을 적용한다.

backend/src/main/java/com/woowacourse/gongcheck/application/TaskService.java, backend/src/main/java/com/woowacourse/gongcheck/application/response/JobActiveResponse.java, backend/src/main/java/com/woowacourse/gongcheck/presentation/TaskController.java, backend/src/test/java/com/woowacourse/gongcheck/acceptance/TaskAcceptanceTest.java, backend/src/test/java/com/woowacourse/gongcheck/application/TaskServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/documentation/TaskDocumentation.java
- #55 
- #60 
`isJobActivated()`: hostId와 jobId로 Job을 가져온 후 해당 Job과 연관된 RunningTask가 존재하는지를 확인하여 참/거짓을 응답합니다.
#60 해당 이슈 사항에 따라 isActive 필드를 active로 변경합니다.
=> [BE] 진행 중인 작업이 있는지 확인할 수 있는 API를 만든다

backend/src/main/java/com/woowacourse/gongcheck/application/TaskService.java, backend/src/main/java/com/woowacourse/gongcheck/domain/task/RunningTask.java, backend/src/main/java/com/woowacourse/gongcheck/domain/task/RunningTaskRepository.java, backend/src/main/java/com/woowacourse/gongcheck/domain/task/TaskRepository.java, backend/src/main/java/com/woowacourse/gongcheck/presentation/TaskController.java, backend/src/test/java/com/woowacourse/gongcheck/acceptance/TaskAcceptanceTest.java, backend/src/test/java/com/woowacourse/gongcheck/application/TaskServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/documentation/TaskDocumentation.java, backend/src/test/java/com/woowacourse/gongcheck/domain/task/RunningTaskRepositoryTest.java, backend/src/test/java/com/woowacourse/gongcheck/domain/task/RunningTaskTest.java, backend/src/test/java/com/woowacourse/gongcheck/domain/task/TaskRepositoryTest.java, backend/src/test/java/com/woowacourse/gongcheck/fixture/FixtureFactory.java, backend/src/test/java/com/woowacourse/gongcheck/presentation/TaskControllerTest.java
- #57 
```
POST /api/tasks/{taskId}/complete HTTP/1.1
Authorization : Bearer jwt.token.here
statusCode: 200 OK
```
체크 박스를 누를 때 호출되는 API입니다.
RunningTask의 상태가 false일 경우, true로 변경하고
true일 경우, false로 변경합니다.
```java
Optional<RunningTask> findByTaskSectionJobSpaceHostAndTaskId(final Host host, final Long taskId);
```
현재 RunningTask를 조회할 때 join되는 테이블이 많습니다.
=> [BE] 진행중인 작업을 체크하는 API를 구현한다. 

.github/workflows/backend.yml, .github/workflows/frontend.yml, backend/build.gradle, frontend/sonar-project.properties, sonar-project.properties
- resolve #113 
- backend, frontend 각각의 폴더에서 변경점이 일어난 pull request 요청시 트리거가 발생하여 해당하는 폴더에 대한 analysis만 진행한다.
- 프론트의 경우 현재 테스트코드가 존재하지 않기 때문에 coverage가 항상 0으로 동작하므로 이점 유의하여 차후에 추가논의를 생각하여야 함
=> [ALL] SonarCloud 정적분석을 추가한다.

frontend/src/layouts/HostLayout/index.tsx
- resolve #156 
- ex)
- /host/manage/ 
- /host/manage/spaceCreate
- 등등.. 하위 계층에 속성이 적용안되는 이슈 수정
=> [FE] /host/manage URL 하위 계층에 HostLayout padding-left 속성을 적용한다.

frontend/src/Routes.tsx, frontend/src/layouts/UserLayout/index.tsx, frontend/src/pages/user/Password/index.tsx, frontend/src/pages/user/Password/styles.ts, frontend/src/pages/user/Password/usePassword.ts
- resolve #98 
- resolve #108 
- 비밀번호 페이지 구현
- UserLayout에서 사용자의 토큰이 없을경우 password 페이지로 리다이렌션 시켰습니다.
=> [FE] 비밀번호 페이지를 생성한다.

frontend/src/components/TaskCard/styles.ts, frontend/src/components/_common/Checkbox/styles.ts, frontend/src/pages/user/TaskList/index.tsx, frontend/src/pages/user/TaskList/styles.ts
- resolve #128 
- 사용자 체크리스트 페이지 새로운 UI 구현
- progressbar 구현
=> [FE] 사용자, 체크리스트 페이지 새로운 UI 구현

backend/src/test/java/com/woowacourse/gongcheck/documentation/SubmissionDocumentation.java
- resolve #171 
- 누락되었던 Documentation 테스트 데이터를 추가했습니다.
=> [BE] 테스트 데이터 수정

.github/workflows/backend.yml, .github/workflows/frontend.yml
- resolve #185 
- main에서 dev로 github action 트리거 브랜치 수정
=> [ALL] github action 목표 브랜치를 dev로 변경한다.

.github/workflows/backend.yml, .github/workflows/frontend.yml
- resolve #193 
- github action script submodule remove
=> [ALL] github action script submodule remove

frontend/src/layouts/UserLayout/index.tsx
- resolve #198 
- errorBoundary 디렉토리 이름 수정
=> [FE] errorBoundary 디렉토리 이름 수정

frontend/src/apis/job.ts, frontend/src/apis/slack.ts, frontend/src/components/common/Dimmer/index.tsx, frontend/src/components/host/JobListCard/index.tsx, frontend/src/components/host/JobListCard/styles.ts, frontend/src/components/host/SectionCard/index.tsx, frontend/src/components/host/SlackUrlBox/index.tsx, frontend/src/components/host/SlackUrlBox/styles.ts, frontend/src/components/host/SlackUrlModal/index.tsx, frontend/src/components/host/SlackUrlModal/styles.ts, frontend/src/components/host/SpaceInfo/index.tsx, frontend/src/components/host/TaskBox/index.tsx, frontend/src/components/user/SpaceCard/index.tsx, frontend/src/components/user/TaskCard/index.tsx, frontend/src/layouts/ManageLayout/index.tsx, frontend/src/layouts/UserLayout/index.tsx, frontend/src/pages/host/AuthCallBack/index.tsx, frontend/src/pages/host/AuthCallBack/styles.ts, frontend/src/pages/host/DashBoard/index.tsx, frontend/src/pages/host/DashBoard/styles.ts, frontend/src/pages/host/SpaceCreate/index.tsx, frontend/src/pages/user/Password/index.tsx, frontend/src/pages/user/Password/usePassword.ts, frontend/src/pages/user/TaskList/index.tsx, frontend/src/styles/global.ts
- resolve #200 
- 컨벤션 맞추기 위해서 이벤트핸들러 handle 네이밍을 on으로 일괄수정해서 fileChange가 생각보다 많습니다.. 해당 부분은 무시하고 보셔도 무관합니다
- 백엔드 API가 머지되지 않은 부분이 있어서 더미데이터로만 돌아가게 해놨고 로직은 주석처리 해놓았습니다.
- 공간 생성 API 로직이 연동되면 주석제거하겠습니다.
- 스타일링 맞추는 코드도 해당 PR에 들어있습니다.
=> [FE] 슬랙 URL 조회 및 수정 API를 연동한다.

backend/src/main/java/com/woowacourse/gongcheck/application/JobService.java, backend/src/main/java/com/woowacourse/gongcheck/application/response/SlackUrlResponse.java, backend/src/main/java/com/woowacourse/gongcheck/domain/job/Job.java, backend/src/main/java/com/woowacourse/gongcheck/presentation/JobController.java, backend/src/main/java/com/woowacourse/gongcheck/presentation/request/SlackUrlChangeRequest.java, backend/src/test/java/com/woowacourse/gongcheck/acceptance/JobAcceptanceTest.java, backend/src/test/java/com/woowacourse/gongcheck/application/JobServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/documentation/JobDocumentation.java, backend/src/test/java/com/woowacourse/gongcheck/domain/job/JobTest.java, backend/src/test/java/com/woowacourse/gongcheck/fixture/FixtureFactory.java, backend/src/test/resources/data.sql
- resolve #145 
- Job의 SlackUrl 조회 및 수정 기능입니다.
=> [BE] SlackUrl 조회 및 수정 기능을 구현한다.

backend/src/main/java/com/woowacourse/gongcheck/application/JobService.java, backend/src/main/java/com/woowacourse/gongcheck/domain/section/SectionRepository.java, backend/src/main/java/com/woowacourse/gongcheck/presentation/JobController.java, backend/src/test/java/com/woowacourse/gongcheck/acceptance/JobAcceptanceTest.java, backend/src/test/java/com/woowacourse/gongcheck/application/JobServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/documentation/JobDocumentation.java, backend/src/test/java/com/woowacourse/gongcheck/domain/section/SectionRepositoryTest.java
- resolve #174 
- Space 삭제 API랑 흐름이 똑같습니다.
- 특별한 사항 없습니다!
=> [BE] Job 삭제 API를 구현한다.

frontend/src/apis/space.ts, frontend/src/components/host/SpaceInfo/index.tsx, frontend/src/components/host/SpaceInfo/useSpaceInfo.ts, frontend/src/pages/host/SpaceCreate/index.tsx, frontend/src/pages/host/SpaceCreate/styles.ts, frontend/src/pages/host/SpaceCreate/useSpaceCreate.ts, frontend/src/pages/host/SpaceModify/index.tsx
- resolve #159 
- 공간 생성 플로우에 맞게 비지니스 로직, API 연동 구현
=> [FE] 공간 생성 플로우에 맞게 비지니스 로직, API 연동을 구현해야 한다.

backend/src/main/resources/dummy_data.sql
- resolve #142 
- 데모데이 시연용 더미데이터의 값을 변경했습니다. "잠실" -> "잠실 캠퍼스"
=> [BE] 테이블에 있는 잠실, 선릉 공간의 이름을 변경한다.

backend/src/test/java/com/woowacourse/gongcheck/acceptance/GuestAuthAcceptanceTest.java, backend/src/test/java/com/woowacourse/gongcheck/acceptance/HostAcceptanceTest.java, backend/src/test/java/com/woowacourse/gongcheck/acceptance/SubmissionAcceptanceTest.java, backend/src/test/java/com/woowacourse/gongcheck/acceptance/TaskAcceptanceTest.java, backend/src/test/java/com/woowacourse/gongcheck/application/SubmissionServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/application/TaskServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/documentation/SpaceDocumentation.java, backend/src/test/java/com/woowacourse/gongcheck/documentation/SubmissionDocumentation.java, backend/src/test/java/com/woowacourse/gongcheck/documentation/TaskDocumentation.java, backend/src/test/java/com/woowacourse/gongcheck/domain/job/JobRepositoryTest.java, backend/src/test/java/com/woowacourse/gongcheck/domain/task/RunningTaskRepositoryTest.java, backend/src/test/java/com/woowacourse/gongcheck/domain/task/RunningTaskTest.java, backend/src/test/java/com/woowacourse/gongcheck/domain/task/RunningTasksTest.java
- resolve #151 
* 멤버 -> Host
* 공간 -> Space
* 현재 진행 중인 작업 -> RunningTask
* 진행작업을 체크한다 or 체크박스를 체크한다 -> RunningTask의 체크상태를 변경한다
* 작업 -> Job
* 제출한다 -> Submission을 생성한다
=> [BE] 테스트 메서드에서 도메인 명을 영어로 사용하도록 변경한다

frontend/src/components/user/NameModal/index.tsx, frontend/src/components/user/NameModal/useNameModal.ts, frontend/src/pages/user/TaskList/useTaskList.tsx
- resolve #236 
- URL에 정상적으로 hostId가 나오게 수정한다.
고려 할점
- 모달에서 useParams를 못 읽는다.
- 좀 더 확인을 해봐야할 상황이다.
=> [FE] 사용자, 체크리스트에서 이름 제출 후, URL에 undefined 나오는 이슈를 해결한다.

frontend/src/components/common/Loading/index.tsx, frontend/src/components/common/Loading/styles.ts, frontend/src/components/host/SlackUrlModal/index.tsx, frontend/src/layouts/HostLayout/index.tsx, frontend/src/styles/animation.ts
- resolve #229 
- 관리자 로딩 스피터 구현
고려 사항
- suspense fullback이 로딩 컴포넌트를 전체 영역으로 채우는 역할을 하는거 같다.
- 로딩중에는 뒤에 다른 요소들이 보이지 않는다.
=> [FE] 관리자 로딩 스피너를 구현한다.

backend/src/main/resources/application-test.yml, backend/src/test/resources/application.yml
- resolve #204 
- main의 `applicatoin-test.yml`과 test의 `application.yml`이 중복되기 때문에 중복된 부분을 통합하였습니다
=> [BE] test용 yml 파일 중복을 제거한다.

backend/src/main/java/com/woowacourse/gongcheck/presentation/Authority.java, backend/src/main/java/com/woowacourse/gongcheck/presentation/HostController.java, backend/src/main/java/com/woowacourse/gongcheck/presentation/JobController.java, backend/src/main/java/com/woowacourse/gongcheck/presentation/SpaceController.java, backend/src/main/java/com/woowacourse/gongcheck/presentation/SubmissionController.java, backend/src/main/java/com/woowacourse/gongcheck/presentation/aop/HostOnly.java, backend/src/main/java/com/woowacourse/gongcheck/presentation/aop/HostVerifier.java, backend/src/test/java/com/woowacourse/gongcheck/acceptance/AuthSupport.java, backend/src/test/java/com/woowacourse/gongcheck/acceptance/FakeHostAuthController.java, backend/src/test/java/com/woowacourse/gongcheck/acceptance/HostAcceptanceTest.java, backend/src/test/java/com/woowacourse/gongcheck/acceptance/HostAuthAcceptanceTest.java, backend/src/test/java/com/woowacourse/gongcheck/acceptance/JobAcceptanceTest.java, backend/src/test/java/com/woowacourse/gongcheck/acceptance/SpaceAcceptanceTest.java, backend/src/test/java/com/woowacourse/gongcheck/documentation/JobDocumentation.java
- resolve #226 
- HostOnly annotation을 적용했습니다.
- 기존의 Host 요청에서 임시로 Guest 토큰을 사용했던 것을 Host 토큰을 사용한 테스트로 변경했습니다.
- HostOnly 요청 시, Guest 토큰을 사용한 예외 테스트를 추가했습니다.
=> [BE] 인가 AOP 를 적용한다.

frontend/public/index.html, frontend/src/App.tsx, frontend/src/ToastPortal.tsx, frontend/src/components/common/ToastBar/index.tsx, frontend/src/components/common/ToastBar/styles.ts, frontend/src/hooks/useToast.ts, frontend/src/pages/host/JobCreate/useJobCreate.ts, frontend/src/pages/host/SpaceCreate/useSpaceCreate.ts, frontend/src/pages/user/Password/usePassword.ts, frontend/src/recoil/modal.ts
- resolve #240 
- useToast를 사용하시면 됩니다.
```javascript
const { openToast } = useToast();
openToast('SUCCESS', '업무가 생성 되었습니다.');
openToast('ERROR', '실패입니다.');
```
고려할 사항
- 유저 쪽 alert은 비밀번호 페이지만 Toast Bar로 대체 했습니다.
=> [FE] 알림 토스트바를 구현한다.

backend/src/main/java/com/woowacourse/gongcheck/presentation/SpaceController.java, backend/src/test/java/com/woowacourse/gongcheck/acceptance/SpaceAcceptanceTest.java
- resolve #248 
- `GET /api/spaces/{spaceId}` host 권한 제한 제거
=> [BE] Space 단일 조회에 대한 권한을 전체 허용으로 수정한다.

frontend/src/ErrorBoundary/ErrorUserToken.tsx, frontend/src/apis/task.ts, frontend/src/layouts/UserLayout/index.tsx, frontend/src/pages/user/TaskList/useTaskList.tsx
- resolve #253 
- job 체크리스트 데이터가 없으면 페이지 이동하지 않는다.
=> [FE] 사용자, 페이지 이동 시, 다음 페이지에 보여질 데이터가 없으면 페이지 이동을 막아야 한다.

backend/src/test/java/com/woowacourse/gongcheck/application/JobServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/application/TaskServiceTest.java
- resolve #211 
- 특정 기능을 하는 셋업 메서드(setPort, setDocsGiven) 외에 픽스쳐 세팅을 위한 메서드는 모두 setUp으로 변경하였습니다.
=> [BE] BeforeEach 메서드 네이밍 통일

frontend/.gitignore, frontend/package-lock.json, frontend/package.json, frontend/src/apis/config.ts, frontend/webpack.config.js
- resolve #263 
- api 환경 변수 설정을 했다.
=> [FE] 환경변수를 설정한다.

.gitmodules, frontend/webpack.config.js
- resolve #266
- front submodule 추가
=> [FE] front submodule 추가

frontend/src/pages/host/JobCreate/useJobCreate.ts, frontend/src/pages/user/Password/index.tsx
- resolve #268 
- 서버 API 주소를 수정한다.
=> [FE] 환경설정을 수정한다.

backend/src/main/java/com/woowacourse/gongcheck/application/JobService.java, backend/src/main/java/com/woowacourse/gongcheck/application/SpaceService.java, backend/src/main/java/com/woowacourse/gongcheck/application/response/JobsResponse.java, backend/src/main/java/com/woowacourse/gongcheck/application/response/SpacesResponse.java, backend/src/main/java/com/woowacourse/gongcheck/domain/job/JobRepository.java, backend/src/main/java/com/woowacourse/gongcheck/domain/space/SpaceRepository.java, backend/src/main/java/com/woowacourse/gongcheck/presentation/JobController.java, backend/src/main/java/com/woowacourse/gongcheck/presentation/SpaceController.java, backend/src/test/java/com/woowacourse/gongcheck/acceptance/JobAcceptanceTest.java, backend/src/test/java/com/woowacourse/gongcheck/acceptance/SpaceAcceptanceTest.java, backend/src/test/java/com/woowacourse/gongcheck/application/JobServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/application/SpaceServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/documentation/JobDocumentation.java, backend/src/test/java/com/woowacourse/gongcheck/documentation/SpaceDocumentation.java, backend/src/test/java/com/woowacourse/gongcheck/domain/job/JobRepositoryTest.java, backend/src/test/java/com/woowacourse/gongcheck/domain/space/SpaceRepositoryTest.java
- resolve #206 
- Space, Job의 Pageable을 제거했습니다.
- findPage method 명을 각각 findSpaces, findJobs로 변경했습니다.
=> [BE] Space, Job의 Pageable을 제거한다.

frontend/src/pages/user/TaskList/useTaskList.tsx
- resolve #281 
- 동시성, 체크리스트 api 호출을 1초마다 refetch 한다.
- 체크리스트 데이터를 1초마다 api 호출해서 체크리시트 데이터를 업데이트 시킨다.
=> [FE] 동시성, 사용자 체크리스트를 계속 호출해서 동시성을 구현한다.

frontend/src/apis/space.ts, frontend/src/components/host/SpaceDeleteButton/index.tsx, frontend/src/components/host/SpaceDeleteButton/styles.ts, frontend/src/components/host/SpaceDeleteModal/index.tsx, frontend/src/components/host/SpaceDeleteModal/styles.ts, frontend/src/pages/host/DashBoard/index.tsx, frontend/src/pages/host/DashBoard/styles.ts, frontend/src/pages/host/DashBoard/useDashBoard.tsx
- resolve #299 
- 공간 삭제 버튼을 누르면 공간 삭제 모달창이 노출된다.
- 공간 삭제 모달창에서 올바른 텍스트를 입력하면 공간을 삭제 할 수 있다.
- 공간을 삭제하면 모달창이 사라지고 새롭게 공간의 정보를 api 호출을 통해 화면을 리렌더링 한다.
=> [FE] 공간 삭제 기능을 구현한다.

backend/src/test/java/com/woowacourse/gongcheck/core/application/HostServiceTest.java
- resolve #305 
- 참고자료 https://johngrib.github.io/wiki/junit5-nested/
=> [BE] DCI 패턴을 적용한 HostService 테스트 코드를 수정한다.

frontend/package-lock.json, frontend/package.json, frontend/src/apis/config.ts, frontend/src/components/common/GitHubLoginButton/index.tsx, frontend/webpack.config.js
- resolve #315 
- resolve #316 
- resolve #307 
- local, staging, release로 build를 나눈다.
- 각각의 필요한 환경변수를 .env.development, .env.staging, .env.production 분리해서 관리한다.
- 각각의 서비스 환경에서 필요한 github Oauth 로그인 URL 주소를 env 환경변수로 관리한다.
=> [FE] 서버의 서비스 환경에 따라 build를 구분하고 각 build에 필요한 env 환경설정 및 Organization으로 만든 Github Oauth을 연동해야 한다.

backend/src/main/java/com/woowacourse/gongcheck/auth/application/HostAuthService.java, backend/src/main/java/com/woowacourse/gongcheck/auth/application/response/TokenResponse.java, backend/src/main/java/com/woowacourse/gongcheck/infrastructure/oauth/GithubOauthClient.java, backend/src/test/java/com/woowacourse/gongcheck/auth/application/GuestAuthServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/auth/application/HostAuthServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/core/domain/host/HostRepositoryTest.java, backend/src/test/java/com/woowacourse/gongcheck/infrastructure/oauth/GithubOauthClientTest.java
- resolve #319 
- HostSerivce, GuestService, GithubOauthClient, HostRepository
- 1차 pr시 한글로 된 메소드 이름이 길어서 빌드가 터졌습니다.
=> [BE] Host, Guest Auth연관 클래스와 HostRepository에 DCI 패턴을 적용한다.

backend/src/test/java/com/woowacourse/gongcheck/core/application/SpaceServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/core/domain/space/SpaceRepositoryTest.java
- resolve #312 
- DCI 패턴 적용했습니다~
=> [BE] SpaceServiceTest, SpaceRepositoryTest에 DCI 패턴을 적용한다.

backend/src/test/java/com/woowacourse/gongcheck/core/application/SubmissionServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/core/domain/submission/SubmissionRepositoryTest.java
=> [BE] SubmissionServiceTest, SubmissionRepositoryTest에 DCI 패턴을 적용한다.

backend/.gitignore, backend/build.gradle, backend/src/main/resources/application.yml, backend/src/test/java/com/woowacourse/gongcheck/core/application/SubmissionServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/core/domain/submission/SubmissionRepositoryTest.java
- resolve #313 
- resolve #328 
- application-local, application-dev, application-prod로 각각 분리하였습니다.
- 위의 세 파일은 submodule에서 관리하고 있습니다.
- 따라서, staging 서버 배포 스크립트에서 java -jar gongcheck.jar 뒤에 `--spring.profiles.active=dev`를 추가하였습니다.
- prod 서버 배포 스크립트에서 java -jar gongcheck.jar 뒤에 `--spring.profiles.active=prod`를 추가하였습니다.
=> [BE] 각 환경에서 사용할 yml 설정파일을 분리한다.

backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/core/domain/job/JobRepositoryTest.java
- resolve #308 
- JobService, JobRepository 테스트에 DCI 패턴을 적용했습니다.
=> [BE] DCI 패턴을 적용한 JobService, JobRepository 테스트 코드를 수정한다.

backend/src/main/resources/application.yml
- resolve #333 
- yml 문법 오류 수정
=> [BE] yml 파일을 수정한다.

backend/src/main/java/com/woowacourse/gongcheck/core/application/response/RunningTasksResponse.java, backend/src/test/java/com/woowacourse/gongcheck/core/application/HostServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/core/application/TaskServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/core/domain/task/RunningTaskRepositoryTest.java, backend/src/test/java/com/woowacourse/gongcheck/core/domain/task/TaskRepositoryTest.java
=> [BE] DCI 패턴을 적용한 TaskService, RunningTaskService, TaskRepository, RunningTaskRepository 테스트 코드를 수정한다.

backend/src/main/resources/application.yml
- resolve #335 
- application.yml의 기본 설정을 local로 변환했습니다.
=> [BE] application.yml의 기본 설정을 local로 한다.

backend/src/main/java/com/woowacourse/gongcheck/core/application/TaskService.java, backend/src/main/java/com/woowacourse/gongcheck/core/domain/task/Tasks.java, backend/src/test/java/com/woowacourse/gongcheck/core/application/TaskServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/core/domain/task/TasksTest.java
- resolve #277 
- runningTasks 생성 시, 존재하는 Task가 없다면 예외 발생 로직을 추가했습니다.
=> [BE] runningTasks 생성 API 로직을 수정한다.

frontend/src/ErrorBoundary/ErrorUserToken.tsx, frontend/src/components/user/JobCard/index.tsx, frontend/src/components/user/JobCard/useJobCard.ts, frontend/src/components/user/NameModal/index.tsx, frontend/src/components/user/NameModal/styles.ts, frontend/src/hooks/useSectionCheck.ts, frontend/src/pages/user/JobList/index.tsx, frontend/src/pages/user/JobList/useJobList.ts, frontend/src/pages/user/TaskList/index.tsx, frontend/src/pages/user/TaskList/useTaskList.tsx
- resolve #278 
- 수정된 runningTask에 맞게 에러처리 수정하였습니다. 
(navigate 처리가 아예 실행되지 않고 업무가 없는 경우에 runningTask를 생성하려는 경우, 에러메시지를 볼 수 있도록 처리)\
- 기타 리팩토링 진행했습니다.
=> [FE] 유저 화면 TaskList 페이지 관련 에러처리

backend/build.gradle, backend/src/main/resources/application-test.yml, backend/src/main/resources/application.yml, backend/src/main/resources/schema_local.sql
- resolve #357
- mysql 연결을 위한 driver 의존성 추가
- prod, staging환경에 영향가지 않도록 local yml값 수정
=> [BE] staging 환경에 mysql database를 연결한다.

backend/src/main/java/com/woowacourse/gongcheck/core/presentation/ImageUploadController.java, backend/src/test/java/com/woowacourse/gongcheck/acceptance/ImageUploadAcceptanceTest.java, backend/src/test/java/com/woowacourse/gongcheck/documentation/ImageUploadDocumentation.java
- resolve #361
- 카멜케이스가 적용되어있지 않아 수정 `POST /api/image-upload` -> `POST /api/imageUpload`
=> [BE] 이미지 업로드 api를 수정한다.

frontend/src/Routes.tsx, frontend/src/apis/config.ts, frontend/src/apis/job.ts, frontend/src/apis/password.ts, frontend/src/components/common/Loading/styles.ts, frontend/src/components/host/Navigation/index.tsx, frontend/src/components/host/Navigation/useHostNavigation.ts, frontend/src/pages/host/PasswordUpdate/index.tsx, frontend/src/pages/host/PasswordUpdate/styles.ts, frontend/src/pages/host/PasswordUpdate/usePasswordUpdate.ts
- resolve #364
- 공간 비밀번호 변경 기능을 위해 새로운 페이지 생성
=> [FE] 공간 비밀번호 변경 기능을 구현한다.

backend/src/docs/asciidoc/guest.adoc, backend/src/docs/asciidoc/hosts.adoc, backend/src/docs/asciidoc/image-upload.adoc, backend/src/docs/asciidoc/job.adoc, backend/src/docs/asciidoc/runningTask.adoc, backend/src/docs/asciidoc/space.adoc, backend/src/docs/asciidoc/submission.adoc, backend/src/docs/asciidoc/task.adoc, backend/src/test/java/com/woowacourse/gongcheck/documentation/GuestAuthDocumentation.java, backend/src/test/java/com/woowacourse/gongcheck/documentation/HostAuthDocumentation.java, backend/src/test/java/com/woowacourse/gongcheck/documentation/HostDocumentation.java, backend/src/test/java/com/woowacourse/gongcheck/documentation/ImageUploadDocumentation.java, backend/src/test/java/com/woowacourse/gongcheck/documentation/JobDocumentation.java, backend/src/test/java/com/woowacourse/gongcheck/documentation/SpaceDocumentation.java, backend/src/test/java/com/woowacourse/gongcheck/documentation/SubmissionDocumentation.java, backend/src/test/java/com/woowacourse/gongcheck/documentation/TaskDocumentation.java, backend/src/test/java/com/woowacourse/gongcheck/fixture/FixtureFactory.java
- resolve #351
- RestDocs에 path-parameters, request-fields, response-fields adoc을 추가하였습니다.
- 단순 노가다 작업이라 코드 설명은 따로 할 것이 없네요...
=> [BE] RestDocs 문서를 상세화한다. 

.github/workflows/backend.yml, .github/workflows/frontend.yml
- resolve #388 
- SonarCloud의 500 버그로 인한 관련 빌드 스크립트 제거
=> [ALL] sonar cloud를 임시로 내린다.

frontend/src/components/host/SectionDetailModal/useSectionDetailModal.ts, frontend/src/hooks/useSpaceForm.ts
=> [FE] 이미지 업로드 api 호출시, multipart form 필드명 image로 수정해야한다.

frontend/cypress/e2e/guest.cy.ts
=> [FE] cypress 테스트 코드 에러 나는 부분을 수정한다.

backend/build.gradle, backend/src/main/java/com/woowacourse/gongcheck/core/domain/host/Host.java, backend/src/main/java/com/woowacourse/gongcheck/core/domain/space/Name.java, backend/src/main/java/com/woowacourse/gongcheck/exception/ControllerAdvice.java, backend/src/main/java/com/woowacourse/gongcheck/exception/InfrastructureException.java, backend/src/main/java/com/woowacourse/gongcheck/infrastructure/alert/SlackService.java, backend/src/main/java/com/woowacourse/gongcheck/infrastructure/jwt/JjwtTokenProvider.java, backend/src/main/java/com/woowacourse/gongcheck/infrastructure/oauth/GithubOauthClient.java, backend/src/main/resources/logback-spring.xml, backend/src/main/resources/logback/properties/default-properties.xml, backend/src/main/resources/logback/slack/slack-appender.xml, backend/src/test/java/com/woowacourse/gongcheck/auth/application/GuestAuthServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/core/domain/host/HostTest.java, backend/src/test/java/com/woowacourse/gongcheck/core/domain/space/NameTest.java, backend/src/test/java/com/woowacourse/gongcheck/infrastructure/jwt/JjwtTokenProviderTest.java, backend/src/test/java/com/woowacourse/gongcheck/infrastructure/oauth/GithubOauthClientTest.java
- resolve #354 
- 현재 logback-access 를 통해 HTTP Request 와 Response 를 확인할 수 있습니다.
- ControllerAdvice 를 통해 로깅을 적용했고, `Error` 의 경우 어느 부분에서 에러가 발생하였는지 확인하기 위해 StackTrace 를 로그에 남기도록 하였습니다.
- AOP 를 사용하여 어떤 클래스.메서드에서 예외가 발생하였는지 확인할 수 있도록 리팩터링할 예정입니다.
=> [BE] 로깅을 적용한다.

frontend/src/ErrorBoundary/ErrorUserTask.tsx, frontend/src/layouts/HostLayout/index.tsx, frontend/src/pages/user/TaskList/useTaskList.tsx
- resolve #393 
- 에러 발생시, 공간 선택 페이지로 이동한다.
=> [FE] 관리자가 작업(task)를 수정하면 접속중이던 유저는 에러가 발생한다.

frontend/src/layouts/HostLayout/index.tsx, frontend/src/layouts/UserLayout/index.tsx
=> [FE] ErrorUserTask 를 UserLayout에 적용시켜야 한다.

backend/src/main/java/com/woowacourse/gongcheck/core/domain/image/imageFile/ImageFile.java, imagestorage/src/main/java/com/woowacourse/imagestorage/domain/ImageFile.java
- resolve #408
- 이미지 파일에 대한 제한을 gif를 허용하기로 하여 해당 사항 수정
=> [BE] 이미지 파일의 확장자 제한을 수정한다.

frontend/src/components/host/ImageBox/index.tsx, frontend/src/components/host/ImageBox/useImageBox.ts, frontend/src/components/host/SpaceInfo/index.tsx, frontend/src/components/host/SpaceInfo/useSpaceInfo.ts, frontend/src/hooks/useSpaceForm.ts, frontend/src/pages/host/DashBoard/index.tsx, frontend/src/pages/host/SpaceCreate/index.tsx, frontend/src/pages/host/SpaceUpdate/index.tsx
=> [FE] 공간 관련 이미지 로직을 분리 해야 한다.

frontend/src/layouts/DefaultLayout/index.tsx
=> [FE] 페이지 전환시 모달 자동으로 꺼지도록 수정

frontend/src/ErrorBoundary/ErrorUserTask.tsx, frontend/src/pages/user/TaskList/index.tsx, frontend/src/pages/user/TaskList/useTaskList.tsx
- resolve #414
- ErrorBoundary 관련 에러 메시지랑, 필요없는 호출에 대한 에러메시지가 콘솔에 찍히고있는 상황인데, 에러처리에 대한 구조적인 개선이 필요할거 같습니다.. 우선 배포를 위해 임시로 처리는 해놨는데 다시 개선해보죠
=> [FE] 사용자가 체크리스트 제출했을때, 에러뜨는 부분 수정

frontend/src/pages/user/TaskList/index.tsx, frontend/src/pages/user/TaskList/styles.ts
=> [FE] 사용자 체크리스트 progressBar 위에 고정을 시켜야 한다.

imagestorage/.gitignore, imagestorage/build.gradle, imagestorage/src/main/java/com/woowacourse/imagestorage/application/ImageService.java, imagestorage/src/main/java/com/woowacourse/imagestorage/exception/ControllerAdvice.java, imagestorage/src/main/java/com/woowacourse/imagestorage/exception/ErrorResponse.java, imagestorage/src/main/java/com/woowacourse/imagestorage/presentation/ImageController.java, imagestorage/src/main/resources/logback-access.xml, imagestorage/src/main/resources/logback-spring.xml, imagestorage/src/main/resources/logback/console/console-access-appender.xml, imagestorage/src/main/resources/logback/console/console-appender.xml, imagestorage/src/main/resources/logback/file/file-access-appender.xml, imagestorage/src/main/resources/logback/file/file-debug-appender.xml, imagestorage/src/main/resources/logback/file/file-error-appender.xml, imagestorage/src/main/resources/logback/file/file-info-appender.xml, imagestorage/src/main/resources/logback/file/file-warn-appender.xml, imagestorage/src/main/resources/logback/properties/default-properties.xml, imagestorage/src/test/java/com/woowacourse/imagestorage/application/ImageServiceTest.java
- resolve #426
- 이미지 서버 내 로깅을 백엔드 서버와 동일하게 적용
=> [BE] 이미지 서버 내 로깅을 적용한다.

frontend/src/components/user/NameModal/useNameModal.ts, frontend/src/pages/user/TaskList/styles.ts
=> [FE] 체크리스트 progressbar 마진 속성 수정

frontend/src/pages/host/DashBoard/useDashBoard.tsx
- resolve #422 
- 관리자 페이지에서 복사된 링크 수정
=> [FE] 관리자 페이지에서 복사된 링크 수정

frontend/src/pages/user/TaskList/useTaskList.tsx
=> [FE] refactor: 0.1초로 호출

backend/src/main/java/com/woowacourse/gongcheck/core/application/SubmissionService.java
- resolve #431
- 동시성 이슈로 인하여 제출하기 기능의 isolation 수준을 serializable로 올린다
=> [BE] 제출하기 동시성 이슈 해결

backend/src/main/java/com/woowacourse/gongcheck/core/domain/vo/Description.java, backend/src/test/java/com/woowacourse/gongcheck/core/domain/vo/DescriptionTest.java
- resolve #435 
- 설명은 공백이 가능하도록 수정
=> fix: 설명은 공백이 가능하도록 수정

backend/src/main/java/com/woowacourse/gongcheck/core/application/SubmissionService.java, backend/src/main/java/com/woowacourse/gongcheck/core/domain/job/Job.java, backend/src/main/java/com/woowacourse/gongcheck/core/presentation/SubmissionController.java, backend/src/test/java/com/woowacourse/gongcheck/core/application/SubmissionServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/core/domain/job/JobTest.java, backend/src/test/java/com/woowacourse/gongcheck/documentation/SubmissionDocumentation.java
- resolve #437 
- slack url이 비어있을 때 슬랙알람이 전달되어 에러로그가 발생되는 것을 확인
=> [BE] slack url이 비어있을때 알람이 전송되는 문제를 해결한다.

backend/src/main/java/com/woowacourse/gongcheck/core/application/NotificationService.java, backend/src/main/java/com/woowacourse/gongcheck/core/application/SubmissionService.java, backend/src/main/java/com/woowacourse/gongcheck/infrastructure/notification/SlackService.java, backend/src/test/java/com/woowacourse/gongcheck/acceptance/AcceptanceTest.java, backend/src/test/java/com/woowacourse/gongcheck/documentation/DocumentationTest.java
- resolve #446 
- 새로운 알림 서비스 추가를 고려하여 DB, API를 변경하지 않기로 결정하면서, 수정할만한 부분이 사라졌네요. 네이밍 변경만 추가되었습니다.
Alert는 "위험을 알리다"라는 의미가 강해서 알려준다는 정도의 의미인 Notification으로 네이밍을 수정했습니다.
=> [BE] Slack에 종속되는 네이밍을 Notification으로 추상화한다.

backend/src/main/java/com/woowacourse/gongcheck/core/application/JobService.java, backend/src/main/java/com/woowacourse/gongcheck/core/domain/job/Job.java, backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/core/domain/job/JobTest.java
- resolve #451 
- Job의 이름은 수정하고 Section, Task만 지우고 재생성하는 로직으로 수정하였읍니다..
=> [BE] updateJob 메서드에서 Job을 삭제하지 않고 수정하는 로직으로 변경한다.

frontend/webpack.config.js
- resolve #466 
- `filename: '[name].[옵션].js',`
- 옵션 종류
- hash: 특정 빌드에 해당하느 해쉬값
- 하나의 변경이 일어나면 전체 파일의 해쉬가 변경된다.
- chunkhash: 특정 chunk에 해당하는 해쉬 값
- 변경이 일어난 entry의 hash값만 변경된다.
- contenthash: 각 파일의 내용을 기반으로 hash 값을 생성한다.
> Chunk란? 번들러에 의해 생성되는 하나의 코드 덩어리를 Dynamic import 나 Entry Points 등을 활용하여 분리된 파일들을 의미힌다.
참고 자료
- [[Webpack] hash, chunkhash 그리고 contenthash (캐싱전략)](https://velog.io/@jiseong/Webpack-hash-chunkhash-%EA%B7%B8%EB%A6%AC%EA%B3%A0-contenthash-%EC%BA%90%EC%8B%B1%EC%A0%84%EB%9E%B5)
- [Webpack Caching 전략](https://joshua1988.github.io/web-development/webpack/caching-strategy/)
=> [FE] bundle.js 브라우저 캐시 최적화를 해야한다.(최신의 배포를 사용자가 바라봐야한다.)

frontend/src/pages/host/PasswordUpdate/usePasswordUpdate.ts
- resolve #472 
- 입장코드 변경 성공시 뒤로가기 기능 추가
=> [FE] 비밀번호를 변경 시(host), 뒤로가기 기능이 작동해야 한다. 

frontend/src/ErrorBoundary/ErrorHostToken.tsx, frontend/src/ErrorBoundary/ErrorUserToken.tsx, frontend/src/apis/config.ts, frontend/src/hooks/useGithubLogin.ts, frontend/src/layouts/UserLayout/index.tsx, frontend/src/pages/user/Password/usePassword.ts
- resolve #484 
- sessionStorage에 tokenKey값을 저장하고, tokenKey값을 바탕으로 localStorage에 있는 token으로 서버와 소통한다.
=> [FE] 유저가 enteranceCode를 바탕으로 여러개의 공간을 동시에 사용할 수 있도록 한다. 

backend/src/docs/asciidoc/runningTask.adoc, backend/src/main/java/com/woowacourse/gongcheck/core/application/TaskService.java, backend/src/main/java/com/woowacourse/gongcheck/core/domain/section/SectionRepository.java, backend/src/main/java/com/woowacourse/gongcheck/core/domain/task/RunningTask.java, backend/src/main/java/com/woowacourse/gongcheck/core/domain/task/RunningTasks.java, backend/src/main/java/com/woowacourse/gongcheck/core/domain/task/TaskRepository.java, backend/src/main/java/com/woowacourse/gongcheck/core/domain/task/Tasks.java, backend/src/main/java/com/woowacourse/gongcheck/core/presentation/TaskController.java, backend/src/test/java/com/woowacourse/gongcheck/SupportRepository.java, backend/src/test/java/com/woowacourse/gongcheck/acceptance/TaskAcceptanceTest.java, backend/src/test/java/com/woowacourse/gongcheck/core/application/TaskServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/core/domain/section/SectionRepositoryTest.java, backend/src/test/java/com/woowacourse/gongcheck/core/domain/task/RunningTaskTest.java, backend/src/test/java/com/woowacourse/gongcheck/core/domain/task/RunningTasksTest.java, backend/src/test/java/com/woowacourse/gongcheck/core/domain/task/TaskRepositoryTest.java, backend/src/test/java/com/woowacourse/gongcheck/documentation/TaskDocumentation.java
- resolve #479 
- HostId와 SectionId를 받아 해당 Section의 모든 runningTask를 체크하는 기능을 구현했습니다.
- 동일한 로직의 반복이라 이해하기 어려운 부분은 없으실 것 같아요!
=> [BE] 해당 Section의 모든 runningTask를 체크하는 기능을 구현한다.

frontend/cypress.config.ts, frontend/package-lock.json, frontend/package.json, frontend/tsconfig.json
- #462
- 스크립트 추가
- start-and-test 설치
=> [FE] Cypress CI를 위한 설정 파일 수정

.github/workflows/backend.yml, backend/build.gradle
- resolve #491 
- 기존의 sonarcloude를 제거한 후, sonarqube로 전환했습니다.
- 자세한 설정 과정과 설명은 링크로 추가하겠습니다.
=> [BE] SonarCloud에서 SonarQube로 전환한다.

frontend/src/apis/task.ts, frontend/src/hooks/useSectionCheck.ts, frontend/src/pages/user/TaskList/index.tsx, frontend/src/pages/user/TaskList/styles.ts, frontend/src/pages/user/TaskList/useTaskList.tsx
- resolve #475 
- section 별로 all 체크 버튼을 구현한다.
- section에 전체 체크가 되어 있으면 버튼이 사라진다.
- section에 전체 체크가 안되어 있으면 버튼이 노출된다.
=> [FE] 체크리스트 올 체크 기능을 구현해야한다.

frontend/cypress/e2e/guest.cy.js
=> [FE] 젠킨스에서 에러나는 테스트 코드 주석처리

frontend/src/components/common/Loading/styles.ts, frontend/src/components/common/LoadingOverlay/index.tsx, frontend/src/components/common/LoadingOverlay/styles.ts, frontend/src/components/host/SectionDetailModal/index.tsx, frontend/src/components/host/SectionDetailModal/styles.ts, frontend/src/components/host/SectionDetailModal/useSectionDetailModal.ts, frontend/src/components/host/SpaceInfoCreateBox/index.tsx, frontend/src/components/host/SpaceInfoUpdateBox/index.tsx, frontend/src/hooks/useImage.ts, frontend/src/pages/host/DashBoard/useDashBoard.tsx
=> [FE] 상황별 로딩환경을 개선한다. 

backend/src/main/java/com/woowacourse/gongcheck/core/application/TaskService.java
- resolve #524 
- 해당 Section의 모든 runningTask를 체크 시 반환값을 전체 RunningTask를 반환하도록 수정합니다.
=> [BE] 해당 Section의 모든 runningTask를 체크 시 반환값을 전체 RunningTask를 반환하도록 수정한다.

frontend/src/pages/user/TaskList/useTaskList.tsx
=> fix: 체크리스트 페이지 리다이렉팅 수정

README.md
=> [ALL] README.md 생성 및 내용 작성

frontend/src/components/common/SlideMenu/styles.ts, frontend/src/components/host/Menu/useMenu.ts, frontend/src/components/host/Navigator/TopNavigator/styles.ts, frontend/src/components/host/SpaceInfoCreateBox/styles.ts, frontend/src/components/host/SpaceInfoDisplayBox/styles.ts, frontend/src/components/host/SpaceInfoUpdateBox/styles.ts, frontend/src/components/host/Submissions/styles.ts, frontend/src/pages/host/DashBoard/useDashBoard.tsx
- 버튼 크기 수정
- 메뉴 수정
- 링크는 되는지 봐야함
=> [FE] 모바일 페이지, IOS 최적화 및 수정

frontend/src/hooks/useScroll.ts
- resolve #563 
- 화면을 위로 올리면 scrollPosition 값이 NaN이 되는 이슈를 수정했다.
=> [FE] 랜딩페이지 버그 수정, 모바일 환경에서 위로 올리면 에러 발생하는 이슈

frontend/src/components/host/JobListCard/index.tsx, frontend/src/components/host/JobListCard/styles.ts, frontend/src/components/host/LandingView/HeroSection/index.tsx, frontend/src/components/host/LandingView/HeroSection/styles.ts, frontend/src/components/user/JobCard/index.tsx, frontend/src/components/user/JobCard/styles.ts, frontend/src/components/user/SpaceCard/styles.ts, frontend/src/pages/host/Home/index.tsx, frontend/src/pages/host/Home/styles.ts, frontend/src/pages/user/Password/index.tsx, frontend/src/pages/user/Password/styles.ts, frontend/src/pages/user/SpaceList/index.tsx, frontend/src/pages/user/SpaceList/styles.ts
- resolve #544 
- 이미지 webp 확장자 적용
- aspect-ratio 비율 속성 적용
- [Aspect Ratio, 요소를 비율대로 조정하기](https://mong-blog.tistory.com/entry/css-Aspect-Ratio-%EC%9A%94%EC%86%8C%EB%A5%BC-%EB%B9%84%EC%9C%A8%EB%8C%80%EB%A1%9C-%EC%A1%B0%EC%A0%95%ED%95%98%EA%B8%B0)
- [aspect-ratio mdn](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio)
=> [FE] 다양한 디바이스 사이즈에 맞게 이미지를 보여줘야 한다. (width, height 값 지정, 성능 최적화)

frontend/src/components/host/LandingView/HeroSection/styles.ts, frontend/src/components/host/LandingView/HeroSection/useHeroSection.ts
- resolve #567 
- 스크롤 업을 끝까지 하면 생기는 이슈
- radius 변수값이 음수가 되서 생기는 이슈였습니다.
=> [FE] IOS 환경, 랜딩페이지에서 스크롤 위로 쭉 업 하면 화면이 하얗게 생기는 이슈 #567

frontend/package-lock.json, frontend/package.json, frontend/src/components/host/LandingView/HostPicture/index.tsx, frontend/src/components/host/LandingView/HostViewSection2/index.tsx, frontend/src/components/host/LandingView/UserPicture/index.tsx, frontend/src/components/host/LandingView/UserViewSection1/index.tsx, frontend/src/components/host/LandingView/UserViewSection2/index.tsx, frontend/src/components/host/LandingView/UserViewSection3/index.tsx, frontend/src/types/index.ts
=> [FE] gongcheck util types 모듈 적용

backend/src/main/java/com/woowacourse/gongcheck/core/application/JobService.java, backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
- resolve #547 
- DCI Context 수정 및 누락 테스트 추가했습니다.
=> [BE] JobServiceTest를 개선한다.

backend/src/docs/asciidoc/hosts.adoc, backend/src/main/java/com/woowacourse/gongcheck/auth/application/response/SocialProfileResponse.java, backend/src/main/java/com/woowacourse/gongcheck/core/application/HostService.java, backend/src/main/java/com/woowacourse/gongcheck/core/application/response/EntranceCodeResponse.java, backend/src/main/java/com/woowacourse/gongcheck/core/application/response/HostProfileResponse.java, backend/src/main/java/com/woowacourse/gongcheck/core/domain/host/Host.java, backend/src/main/java/com/woowacourse/gongcheck/core/presentation/HostController.java, backend/src/main/resources/schema_local.sql, backend/src/test/java/com/woowacourse/gongcheck/acceptance/DatabaseInitializer.java, backend/src/test/java/com/woowacourse/gongcheck/acceptance/HostAcceptanceTest.java, backend/src/test/java/com/woowacourse/gongcheck/core/application/HostServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/documentation/HostDocumentation.java, backend/src/test/java/com/woowacourse/gongcheck/fixture/FixtureFactory.java
- resolve #596 
- host에 nickname column을 추가했습니다.
- 이미 가입한 사용자의 nickname은 '닉네임 변경 바람'으로 설정하기로 했습니다.
- 추후 nickname 변경 api를 생성할 예정입니다.
=> [BE] host profile 조회 api를 구현한다.

frontend/src/Routes.tsx, frontend/src/pages/common/NotFound/index.tsx, frontend/src/pages/common/NotFound/styles.ts
=> [FE] 404 에러 페이지 구현 및 잘못된 접근에 대한 예외 상황을 처리해야한다.

backend/src/docs/asciidoc/hosts.adoc, backend/src/main/java/com/woowacourse/gongcheck/auth/application/response/SocialProfileResponse.java, backend/src/main/java/com/woowacourse/gongcheck/core/application/HostService.java, backend/src/main/java/com/woowacourse/gongcheck/core/application/response/HostProfileResponse.java, backend/src/main/java/com/woowacourse/gongcheck/core/domain/host/Host.java, backend/src/main/java/com/woowacourse/gongcheck/core/domain/host/Nickname.java, backend/src/main/java/com/woowacourse/gongcheck/core/presentation/HostController.java, backend/src/main/java/com/woowacourse/gongcheck/core/presentation/request/HostProfileChangeRequest.java, backend/src/main/java/com/woowacourse/gongcheck/exception/ErrorCode.java, backend/src/test/java/com/woowacourse/gongcheck/acceptance/HostAcceptanceTest.java, backend/src/test/java/com/woowacourse/gongcheck/core/application/HostServiceTest.java, backend/src/test/java/com/woowacourse/gongcheck/core/domain/host/HostTest.java, backend/src/test/java/com/woowacourse/gongcheck/core/domain/host/NicknameTest.java, backend/src/test/java/com/woowacourse/gongcheck/documentation/HostDocumentation.java, backend/src/test/java/com/woowacourse/gongcheck/fixture/FixtureFactory.java
- resolve #607  
- profile 상세정보 변경 api를 구현했습니다.
- 현재 변경할 field가 nickname 밖에 없어 nickname만 변경하는 상황입니다.
=> [BE] Host profile 상세정보 변경 api를 구현한다.

frontend/cypress/e2e/guest.cy.js, frontend/src/components/host/LandingView/HeroSection/useHeroSection.ts, frontend/src/hooks/useOnContainerScroll.ts
- resolve #612 
- 랜딩 페이지에 사용되는 hook 코드 정리
=> [FE] landing 페이지 코드 리팩토링

frontend/src/apis/host.ts, frontend/src/components/common/Profile/index.tsx, frontend/src/components/host/Navigator/Menu/index.tsx, frontend/src/components/host/Navigator/Menu/useMenu.ts, frontend/src/pages/user/Password/index.tsx, frontend/src/pages/user/Password/usePassword.ts
- resolve #620
프로필 조회 api의 스펙이 바뀜에 따라 프론트 코드도 변경되었습니다.
=> [FE] 프로필 조회 API 관련 수정 사항 

frontend/src/components/common/LazyImage/index.tsx, frontend/src/components/host/SectionDetailModal/index.tsx, frontend/src/components/host/SectionDetailModal/useSectionDetailModal.ts, frontend/src/components/user/DetailInfoModal/index.tsx, frontend/src/components/user/SectionCard/index.tsx
- resolve #624 
- user 체크리스트 lazy loading 수정
- 디폴트 이미지로 이미지 url 넣은 host, user 로직 수정
=> [FE] user 체크리스트 lazy loading 이슈를 수정한다.

frontend/src/components/host/SectionDetailModal/styles.ts, frontend/src/components/user/DetailInfoModal/index.tsx, frontend/src/components/user/DetailInfoModal/styles.ts, frontend/src/components/user/SectionCard/SectionInfoPreview/index.tsx, frontend/src/components/user/SectionCard/SectionInfoPreview/styles.ts, frontend/src/components/user/SectionCard/index.tsx
- resolve #628 
- 이미지 url 없을 때 썸네일 색깔로 지정했습니다.
- 이미지 없을때 이미지 박스 제거 했습니다.
- 모달창 최대 크기 정했습니다.
=> [FE] 이미지 추가 시, 모달창 최대 크기를 정해야 한다. 디폴트 이미지를 정해야 한다.

frontend/src/pages/user/TaskList/useTaskList.tsx
로컬과 다르게 배포된 환경에서는 웹소켓이 disconnect 되던 현상
=> [FE] 웹소켓 커넥션 끊겼을 상황에 이전 페이지로 이동한다.

frontend/src/hooks/useSocket.ts, frontend/src/pages/user/TaskList/index.tsx, frontend/src/pages/user/TaskList/useTaskList.tsx
- resolve #639 
- 정상적인 뒤로가기 요청에도 에러메시지가 뜨던 현상 해결
=> [FE] 뒤로가기 버튼으로 이전 페이지로 이동하였을때, 나오는 에러메시지를 제거한다. 

frontend/src/hooks/useSocket.ts, frontend/src/pages/user/TaskList/useTaskList.tsx
=> [FE] 작동이 없어 이전 페이지로 이동했을때 메시지를 보여준다.

frontend/src/components/common/LazyImage/index.tsx
- resolve #648 
- onLoad, onError 처리를 합니다.
- 이미지 URL이 유효하다는 전제하에 개선했습니다.
- 데모 날 엑박으로 계속 떠 있는게 보기 싫어서 임시방편으로 리팩토링 했습니다.
- 보통 preload image를 가장 퓨어 하게 구현하는 방식입니다.
=> [FE] 이미지 서버에서 늦게 받아오는 이미지를 계속 호출 하기 위해 LazyImage 로직을 개선해야 한다.

frontend/src/components/user/DetailInfoModal/index.tsx, frontend/src/components/user/DetailInfoModal/styles.ts, frontend/src/styles/theme.ts
=> [FE] 체크리스트 상세보기 모달창, 이미지 스켈레톤 UI를 적용해야한다.
